/**
 * Reply via Gmail — collapsed by default, on every company page.
 *
 * Chat already has this (chat-panel.tsx's ProposalToolFallback): the model
 * calls propose_draft_reply, a human clicks Apply, and a second click sends.
 * This is the same two-step write — draft, then a separate approve-and-send
 * — with a human able to work the fields directly instead of going through
 * chat (SECURITY.md I1 doesn't care which produced the text; only that a
 * human's own click is what commits it). The body field can be typed by
 * hand, or generated/regenerated by the model via /reply/suggest — a plain
 * text-in/text-out call, no draft written, nothing sent — with an optional
 * saved tone (pages/prompts.tsx's library, fetched here read-only) and
 * free-typed extra instructions both folded into the same call; either way
 * the textarea stays editable right up to the click that saves the draft.
 *
 * Collapsed by default because a compose box open on every visit to every
 * company page would be the loudest thing on it — most visits are reading,
 * not replying.
 *
 * Save draft needs raw-message storage (JOBD_BUCKET — resolving the
 * In-Reply-To header off the message being replied to, services/outbound.py)
 * on top of the chat model; /api/chrome's `storage_configured` says so up
 * front rather than letting the click 503. Both writes confirm first: send
 * because it's truly irreversible, save-draft with a recap of exactly who
 * the reply addresses (To and Cc both) before anything leaves the form.
 *
 * To/Cc/subject pre-fill from /reply/context — the same Reply-To-over-From,
 * everyone-minus-you resolution Gmail's own Reply buttons do — with a
 * Reply / Reply-all toggle that resets the recipient lines the way Gmail's
 * two buttons would. Every line stays editable up to the confirm.
 */

import { useEffect, useRef, useState } from "react"
import { Link } from "react-router-dom"
import { toast } from "sonner"
import {
  Check,
  ChevronsUpDown,
  Loader2,
  Mail,
  Reply,
  ReplyAll,
  ScrollText,
  Send,
  Sparkles,
  TriangleAlert,
} from "lucide-react"

import type { CommunicationRow, OutboundDraft } from "@/lib/api"
import {
  useChrome,
  useDraftReply,
  usePrompts,
  useReplyContext,
  useSendReply,
  useSuggestReply,
} from "@/lib/api"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible"
import { Card, CardContent } from "@/components/ui/card"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

const NO_TONE = "none"

/** The thread a reply attaches to. Preference order: the most recent
 *  inbound message that actually resolved a contact address (so "To" comes
 *  pre-filled — contact resolution is incomplete on plenty of real mail, so
 *  this isn't guaranteed), then the most recent inbound message regardless
 *  (still worth replying to, "To" just needs typing), then the most recent
 *  message of either direction so an all-outbound thread (a cold
 *  application with no reply yet) still has something to attach a
 *  follow-up to. Independent of whatever sort/filter the page's own
 *  communications list is currently under. */
function latestThread(rows: CommunicationRow[]): CommunicationRow | null {
  if (rows.length === 0) return null
  const newest = (pool: CommunicationRow[]) =>
    pool.reduce((latest, row) => (row.sent_at > latest.sent_at ? row : latest))
  const inbound = rows.filter((r) => r.direction === "inbound")
  const addressed = inbound.filter((r) => r.contact_address)
  return newest(addressed.length ? addressed : inbound.length ? inbound : rows)
}

export function ReplyBox({ communications }: { communications: CommunicationRow[] }) {
  const [open, setOpen] = useState(false)
  const thread = latestThread(communications)

  if (!thread) return null

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card className="panel rounded-xl py-0">
        <CollapsibleTrigger asChild>
          <button
            type="button"
            className="hover:bg-muted/40 flex w-full items-center gap-2 rounded-xl px-4 py-3 text-left text-[13px] font-semibold transition-colors"
          >
            <span
              aria-hidden
              className="from-primary/15 to-primary/5 text-primary ring-primary/15 grid size-6 place-items-center rounded-md bg-gradient-to-b ring-1"
            >
              <Mail className="size-3.5" />
            </span>
            Reply via Gmail
            <ChevronsUpDown className="text-muted-foreground ml-auto size-3.5" />
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <CardContent className="px-4 pb-4">
            <ReplyForm thread={thread} />
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  )
}

function ReplyForm({ thread }: { thread: CommunicationRow }) {
  const [mode, setMode] = useState<"reply" | "reply_all">("reply")
  const [to, setTo] = useState(thread.contact_address ?? "")
  const [cc, setCc] = useState("")
  const [subject, setSubject] = useState(
    thread.subject && /^re:/i.test(thread.subject.trim())
      ? thread.subject
      : `Re: ${thread.subject ?? ""}`,
  )
  const [body, setBody] = useState("")
  // What Gmail's own Reply / Reply-all would pre-fill, off the raw message.
  // Applied once on arrival and again on each mode switch — the same reset
  // Gmail does — never over a field the user is mid-edit on afterwards.
  const { data: replyCtx } = useReplyContext(thread.id)
  const prefilled = useRef(false)
  useEffect(() => {
    if (prefilled.current || !replyCtx?.ok || !replyCtx.reply) return
    prefilled.current = true
    if (replyCtx.reply.to.length) setTo(replyCtx.reply.to.join(", "))
    if (replyCtx.subject) setSubject(replyCtx.subject)
  }, [replyCtx])
  const switchMode = (next: "reply" | "reply_all") => {
    setMode(next)
    const line = next === "reply" ? replyCtx?.reply : replyCtx?.reply_all
    if (line) {
      setTo(line.to.join(", "))
      setCc(line.cc.join(", "))
    }
  }
  const [extra, setExtra] = useState("")
  const [toneId, setToneId] = useState(NO_TONE)
  const [draft, setDraft] = useState<OutboundDraft | null>(null)
  const draftReply = useDraftReply(thread.id)
  const sendReply = useSendReply()
  const suggestReply = useSuggestReply(thread.id)
  const { data: promptData } = usePrompts()
  const prompts = promptData?.prompts ?? []
  const tone = prompts.find((p) => p.id === toneId)
  // Save draft needs storage; generate/regenerate doesn't (reply_suggest.py
  // never touches it) — only the one button gates on this, not the form.
  const { data: chrome } = useChrome()
  const storageOff = chrome?.storage_configured === false

  const generate = () => {
    // Tone first, then whatever the human typed on top of it — the same
    // order a human would say them in ("professional, and also mention...").
    const combined = [tone?.text, extra.trim()].filter(Boolean).join("\n\n")
    suggestReply.mutate(combined, {
      onSuccess: (r) => {
        if (r.ok && r.body) setBody(r.body)
        else toast.error(r.message ?? "Could not generate a reply.")
      },
      onError: (error) => toast.error((error as Error).message),
    })
  }

  const createDraft = () => {
    if (!to.trim()) {
      toast.error("Needs a recipient.")
      return
    }
    draftReply.mutate(
      {
        to: to.split(",").map((a) => a.trim()).filter(Boolean),
        cc: cc.split(",").map((a) => a.trim()).filter(Boolean),
        subject,
        body,
      },
      {
        onSuccess: (r) => {
          if (r.ok && r.draft) {
            setDraft(r.draft)
            toast.success("Drafted in Gmail.")
          } else {
            toast.error(r.message ?? "Could not draft this.")
          }
        },
        onError: (error) => toast.error((error as Error).message),
      },
    )
  }

  const send = () => {
    if (!draft) return
    sendReply.mutate(draft.id, {
      onSuccess: (r) => {
        if (r.ok && r.draft) {
          setDraft(r.draft)
          toast.success("Sent.")
        } else {
          toast.error(r.message ?? "Could not send this.")
        }
      },
      onError: (error) => toast.error((error as Error).message),
    })
  }

  if (draft?.status === "sent") {
    return (
      <p className="text-[12.5px] font-medium">
        <Check className="mr-1 inline size-3.5" /> Sent to {draft.recipients.join(", ")}.
      </p>
    )
  }

  return (
    <div className="flex flex-col gap-2.5">
      {!draft && (
        <ToggleGroup
          type="single"
          size="sm"
          variant="outline"
          value={mode}
          onValueChange={(v) => v && switchMode(v as "reply" | "reply_all")}
          className="w-fit"
        >
          <ToggleGroupItem value="reply" className="h-7 gap-1 px-2.5 text-[11.5px]">
            <Reply className="size-3" /> Reply
          </ToggleGroupItem>
          <ToggleGroupItem value="reply_all" className="h-7 gap-1 px-2.5 text-[11.5px]">
            <ReplyAll className="size-3" /> Reply all
          </ToggleGroupItem>
        </ToggleGroup>
      )}
      <div className="grid gap-2 sm:grid-cols-[1fr_1fr]">
        <div className="grid gap-1">
          <Label htmlFor="reply-to" className="text-[11px]">
            To
          </Label>
          <Input
            id="reply-to"
            value={to}
            onChange={(e) => setTo(e.target.value)}
            disabled={!!draft}
            className="h-8 text-xs"
          />
        </div>
        <div className="grid gap-1">
          <Label htmlFor="reply-cc" className="text-[11px]">
            Cc
          </Label>
          <Input
            id="reply-cc"
            value={cc}
            onChange={(e) => setCc(e.target.value)}
            disabled={!!draft}
            placeholder={mode === "reply_all" ? "" : "Nobody cc'd"}
            className="h-8 text-xs"
          />
        </div>
      </div>
      <div className="grid gap-1">
        <Label htmlFor="reply-subject" className="text-[11px]">
          Subject
        </Label>
        <Input
          id="reply-subject"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
          disabled={!!draft}
          className="h-8 text-xs"
        />
      </div>
      {!draft && (
        <div className="flex flex-wrap items-center gap-1.5">
          <Select value={toneId} onValueChange={setToneId}>
            <SelectTrigger size="sm" className="h-8 w-36 text-xs" aria-label="Tone">
              <SelectValue placeholder="Tone" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value={NO_TONE}>No tone</SelectItem>
              {prompts.map((p) => (
                <SelectItem key={p.id} value={p.id}>
                  {p.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input
            value={extra}
            onChange={(e) => setExtra(e.target.value)}
            placeholder="Extra instructions (optional)…"
            className="h-8 min-w-40 flex-1 text-xs"
            onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), generate())}
          />
          <Button
            type="button"
            size="sm"
            variant="outline"
            className="shrink-0"
            disabled={suggestReply.isPending}
            onClick={generate}
          >
            {suggestReply.isPending ? (
              <Loader2 className="animate-spin" />
            ) : (
              <Sparkles />
            )}
            {suggestReply.isPending ? "Generating…" : body.trim() ? "Regenerate" : "Generate reply"}
          </Button>
          <Button asChild size="sm" variant="ghost" className="text-muted-foreground shrink-0" title="Manage saved prompts">
            <Link to="/prompts">
              <ScrollText className="size-3.5" />
            </Link>
          </Button>
        </div>
      )}
      <div className="grid gap-1">
        <Label htmlFor="reply-body" className="text-[11px]">
          Body
        </Label>
        <Textarea
          id="reply-body"
          value={body}
          onChange={(e) => setBody(e.target.value)}
          disabled={!!draft}
          rows={6}
          placeholder="Write your reply, or generate one above…"
          className="text-[13px]"
        />
      </div>
      {!draft ? (
        <div className="flex flex-col gap-1.5">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button
                size="sm"
                variant="outline"
                className="w-fit"
                disabled={draftReply.isPending || storageOff}
                title={storageOff ? "Raw message storage isn't configured — see below" : undefined}
              >
                {draftReply.isPending ? <Loader2 className="animate-spin" /> : <Mail />}
                {draftReply.isPending ? "Drafting…" : "Save draft"}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Save this draft to Gmail?</AlertDialogTitle>
                <AlertDialogDescription>
                  "{subject}" — to {to || "nobody"}
                  {cc.trim() ? `, cc ${cc}` : ""}. Nothing is sent: it lands in
                  your Gmail Drafts, threaded into the conversation, editable
                  there or here.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={createDraft}>Save draft</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
          {storageOff && (
            <p className="text-muted-foreground flex items-start gap-1.5 text-[11px]">
              <TriangleAlert className="mt-0.5 size-3 shrink-0" />
              Raw message storage isn't configured on this server — set{" "}
              <code className="bg-muted rounded px-1 py-0.5 font-mono text-[10.5px]">
                JOBD_BUCKET
              </code>{" "}
              and restart to turn this on.
            </p>
          )}
        </div>
      ) : (
        <div className="flex items-center gap-2">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button size="sm" disabled={sendReply.isPending}>
                {sendReply.isPending ? <Loader2 className="animate-spin" /> : <Send />}
                {sendReply.isPending ? "Sending…" : "Send"}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Send this email?</AlertDialogTitle>
                <AlertDialogDescription>
                  Going to {draft.recipients.join(", ")}. This can't be undone — Gmail
                  will keep the draft to edit, but a sent message isn't recallable.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={send}>Send</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
          <span className="text-muted-foreground text-[11px]">
            Drafted — check Gmail, or send from here.
          </span>
        </div>
      )}
    </div>
  )
}
