"""Plain-SQL migrations, up and down (M3 gate 1).

No ORM and no Alembic. The PRD picks no ORM, and adopting one here would decide
that question by accident, in the milestone least able to argue about it. Plain
SQL also makes the *down* direction real work rather than autogenerated
guesswork — and down is half the gate.

Two safeguards worth naming:

* **Every migration must ship a ``.down.sql``.** A missing one is an error at
  discovery time, not a surprise the first time somebody needs to roll back.
* **Applied migrations are checksummed.** Editing a migration that has already
  run produces a database nobody can reproduce from the repo; this refuses to
  proceed instead of pretending the file on disk is what ran.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

import psycopg

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent.parent / "migrations"

_FILENAME = re.compile(r"^(?P<version>\d{4})_(?P<name>[a-z0-9_]+)\.up\.sql$")

_BOOTSTRAP = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version    integer PRIMARY KEY,
    name       text        NOT NULL,
    checksum   text        NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now()
)
"""


class MigrationError(RuntimeError):
    """Raised when the migration set on disk and the database disagree."""


@dataclass(frozen=True, slots=True)
class Migration:
    """One versioned pair of SQL files."""

    version: int
    name: str
    up_sql: str
    down_sql: str

    @property
    def checksum(self) -> str:
        """Hash of the up SQL. Changing an applied migration changes this."""
        return hashlib.sha256(self.up_sql.encode("utf-8")).hexdigest()

    def __str__(self) -> str:
        return f"{self.version:04d}_{self.name}"


def discover(directory: Path = MIGRATIONS_DIR) -> list[Migration]:
    """Load every migration in a directory, ordered by version.

    Raises:
        MigrationError: If a version is duplicated, or an up file has no
            matching down file.
    """
    found: dict[int, Migration] = {}
    for up_path in sorted(directory.glob("*.up.sql")):
        match = _FILENAME.match(up_path.name)
        if match is None:
            raise MigrationError(
                f"{up_path.name}: expected NNNN_name.up.sql (four digits, "
                "lowercase name)"
            )
        version = int(match["version"])
        down_path = up_path.with_name(f"{match['version']}_{match['name']}.down.sql")
        if not down_path.is_file():
            raise MigrationError(
                f"{up_path.name} has no {down_path.name}. Every migration must be "
                "reversible — M3 gate 1 is up *and* down."
            )
        if version in found:
            raise MigrationError(f"duplicate migration version {version:04d}")
        found[version] = Migration(
            version=version,
            name=match["name"],
            up_sql=up_path.read_text(encoding="utf-8"),
            down_sql=down_path.read_text(encoding="utf-8"),
        )
    return [found[v] for v in sorted(found)]


class Migrator:
    """Applies and reverses migrations against one database.

    Args:
        dsn: libpq connection string, normally ``DATABASE_URL``.
        directory: Where the SQL lives. Overridden in tests.
    """

    def __init__(self, dsn: str, directory: Path = MIGRATIONS_DIR) -> None:
        self._dsn = dsn
        self._migrations = discover(directory)

    @property
    def all(self) -> list[Migration]:
        """Every migration on disk, in order."""
        return list(self._migrations)

    def applied(self) -> dict[int, str]:
        """Version → checksum, for what the database says it has run."""
        with psycopg.connect(self._dsn) as conn:
            conn.execute(_BOOTSTRAP)
            rows = conn.execute(
                "SELECT version, checksum FROM schema_migrations ORDER BY version"
            ).fetchall()
        return {int(version): str(checksum) for version, checksum in rows}

    def _verify(self, applied: dict[int, str]) -> None:
        """Refuse to continue if an already-applied migration has been edited.

        The database cannot be reproduced from a repo whose migrations no longer
        match what ran. Failing here is recoverable; discovering it during a
        rebuild months later is not.
        """
        by_version = {m.version: m for m in self._migrations}
        for version, checksum in applied.items():
            migration = by_version.get(version)
            if migration is None:
                raise MigrationError(
                    f"database has migration {version:04d} applied, but it is not "
                    "in this repo. Wrong branch, or a deleted migration."
                )
            if migration.checksum != checksum:
                raise MigrationError(
                    f"{migration} was edited after it was applied. Roll it back, "
                    "or add a new migration — never edit an applied one."
                )

    def pending(self) -> list[Migration]:
        """Migrations on disk that the database has not run."""
        applied = self.applied()
        self._verify(applied)
        return [m for m in self._migrations if m.version not in applied]

    def up(self, to: int | None = None) -> list[str]:
        """Apply pending migrations up to ``to`` (inclusive). Returns their names.

        Each migration runs in its own transaction, so a failure halfway through
        a set leaves the database on the last migration that fully succeeded —
        never in a half-applied state.
        """
        done: list[str] = []
        for migration in self.pending():
            if to is not None and migration.version > to:
                break
            with psycopg.connect(self._dsn) as conn:
                conn.execute(_BOOTSTRAP)
                conn.execute(migration.up_sql)
                conn.execute(
                    "INSERT INTO schema_migrations (version, name, checksum) "
                    "VALUES (%s, %s, %s)",
                    (migration.version, migration.name, migration.checksum),
                )
            done.append(str(migration))
        return done

    def down(self, to: int = 0) -> list[str]:
        """Reverse applied migrations down to ``to`` (exclusive). Newest first.

        ``to=0``, the default, empties the database — including the
        ``schema_migrations`` ledger, since nothing is left to record. That is
        exactly what gate 1 checks, so it is the default rather than a flag
        somebody has to know.
        """
        applied = self.applied()
        self._verify(applied)
        reverted: list[str] = []
        for migration in reversed(self._migrations):
            if migration.version not in applied or migration.version <= to:
                continue
            with psycopg.connect(self._dsn) as conn:
                conn.execute(migration.down_sql)
                conn.execute(
                    "DELETE FROM schema_migrations WHERE version = %s",
                    (migration.version,),
                )
            reverted.append(str(migration))

        # Nothing applied and nothing to track: drop the ledger too. Gate 1 says
        # *empty*, and a leftover bookkeeping table is the kind of residue that
        # makes "does the down migration really work?" un-answerable by looking.
        if to == 0:
            with psycopg.connect(self._dsn) as conn:
                conn.execute("DROP TABLE IF EXISTS schema_migrations")
        return reverted
